name: "upload_sarif"

# Run workflow each time code is pushed to your repository and on a schedule.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
           distribution: 'temurin'
           java-version: '17'

      - name: Generate SARIF report
        env:
           METERIAN_API_TOKEN: ${{secrets.METERIAN_API_TOKEN}}
           METERIAN_DOWNLOAD_URL: ${{secrets.METERIAN_DOWNLOAD_URL}}
        run: |
           curl meterian-cli.jar -s -O -L -J  $METERIAN_DOWNLOAD_URL
           java -jar -Denv=qa meterian-cli-jar --report-sarif=report.sarif
           rm meterian-cli.jar

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: report.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: my-analysis-tool
